const fs = require('fs')
const path = require('path')

const regenerate = require('regenerate')

const set = regenerate()
  .addRange(0x0, 0x10ffff) // Everything
  .remove(require('unicode-12.1.0/Binary_Property/Alphabetic/code-points.js')) // Overlaps General_Category/Other_Symbol
  .remove(require('unicode-12.1.0/General_Category/Connector_Punctuation/code-points.js'))
  .remove(require('unicode-12.1.0/General_Category/Decimal_Number/code-points.js'))
  .remove(require('unicode-12.1.0/General_Category/Enclosing_Mark/code-points.js'))
  .remove(require('unicode-12.1.0/General_Category/Nonspacing_Mark/code-points.js'))
  .remove(require('unicode-12.1.0/General_Category/Space_Separator/code-points.js'))
  .remove(require('unicode-12.1.0/General_Category/Spacing_Mark/code-points.js'))
  .remove('-') // General_Category/Dash_Punctuation exception

console.log(`/${set.toString()}/g`)
// Then you might want to use a template like this to write the result to a file, along with any regex flags you might need:
// const regex = /<%= set.toString() %>/gim;

fs.writeFileSync(path.resolve('..', '_generated_unicode_regex.js'), `
/* *********************** *\\
 * DO NOT EDIT THIS FILE!
 * It was generated by script/generate-regex.js! Edit the script and run it again instead!
\\* *********************** */

module.exports = function () {
  return /${set.toString()}/g
}
`)
